version: 2
updates:
  - package-ecosystem: "yarn"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    target-branch: "master"
  - package-ecosystem: "yarn"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "tuesday"
    open-pull-requests-limit: 5
    target-branch: "master"
